### ISSUE TITLE
GWLB endpoint costs are not calculated

### ISSUE THREAD

**Issue by mbrightcpacket** [aws-samples/networking-costs-calculator#62]
Hi there! 👋 

Very neat concept! I think there's a bug when clicking the "Gateway LB: Distributed".

Steps to reproduce

1. Deploy 1360a78988bdeb04f689d81a3f1cc628488a8b32.
2. Click the "Gateway LB: Distributed" option by itself.
3. Attempt to set the number GWLB endpoints to number > 1

Expected result

The number of GWLB endpoints is increased and the cost is reflected under "Recurring Costs" and "Data Processing Costs".

Actual result

NaNs for the GWLBe for monthly "Recurring Costs" and "Data Processing Costs".

<img width="1356" alt="screenshot 350" src="https://github.com/user-attachments/assets/697c1e72-18a1-4ea5-82ac-24974bd3f3f4">

**Comment by moshe-shelly** [comment]
looking into it

**Comment by sergioncp** [comment]
fixed it, creating a PR
